### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by imin314** [Azmodan95/rangeSlider#12]
Добавлю сюда то, что обсуждали в телеграмме.

Сейчас модель позволяет управлять всеми своими настройками. В этом подходе, конечно, есть большой плюс, что из-за наличия множества методов событий для каждого свойства не приходится полностью обновлять DOM. Но с другой стороны, если модель изменится, то придется и в вид, и в контроллер добавлять новые однотипные методы для поддержки этих свойств.

Мне кажется, лучше в модели оставить возможность менять только текущие значения, а остальные настройки делать неизменяемыми. У модели не будет методов для установки опций. Она только получает их из класса плагина, а позволяет изменять только текущие значения (value: min & max). Это приводит к тому, что при каждом изменении настроек плагин пересоздает модель, вид и презентер заново.
Изменение количества опций не приведёт к тому что придётся менять презентер или вид (смотря какие настройки, конечно, добавляются). Минус - очевидно, перерисовка DOM. 

Но. В случае слайдера перерисовка DOM не кажется мне большой проблемой, поскольку вариант с тем, что настройки плагина меняются на ходу, - это чисто учебный use case. Как правило, разработчик добавляет плагин с предопределёнными настройками и больше не меняет их.

**Comment by Azmodan95** [comment]
> Мне кажется, лучше в модели оставить возможность менять только текущие значения, а остальные настройки делать неизменяемыми. У модели не будет методов для установки опций. Она только получает их из класса плагина, а позволяет изменять только текущие значения (value: min & max). Это приводит к тому, что при каждом изменении настроек плагин пересоздает модель, вид и презентер заново.

А это не будет противоречить требованию "возможность на лету изменить значение "снаружи" javascript-ом"? Так как данном случае мы вместо того чтобы менять значение, будем пересоздавать заново слайдер.

**Comment by imin314** [comment]
Мне кажется, в IModelOptions лучше перенести свойства из вложенного объекта options на уровень выше:
![Выделение_313](https://user-images.githubusercontent.com/40715953/81686152-95511600-9482-11ea-9ea4-22915c6d99b8.png)

Тогда ты сможешь просто указать `options: IModelOptions` в конструкторе и когда объявляешь публичное свойство модели `options`.

**Comment by imin314** [comment]
Метод setValueMin():
-  Здесь, мне кажется, тоже вместо многократных вызовов getRangeMin() etc лучше скопировать значения в переменные.
- По методу Model.cap не совсем очевидно, что он делает. Может быть, было бы нагляднее заменить его на `Math.min(rangeMin, Math.max(rangeMax, value))`?
https://github.com/Azmodan95/rangeSlider/blob/3917d8e519660174ede393f1ab50b27ce370066d/src/plugin/RangeSlider/Model/Model.ts#L101-L111

**Comment by Azmodan95** [comment]
> **IModelOptions:**
> Предлагаю упростить структуру опций модели, избавив ее от вложенных объектов. Вложенные объекты здесь не очень удобны, на мой взгляд, во-первых, потому что нельзя просто скопировать объект - приходится использовать костыль JSON.parse(JSON.stringify).
> https://github.com/Azmodan95/rangeSlider/blob/3917d8e519660174ede393f1ab50b27ce370066d/src/plugin/RangeSlider/Model/Model.ts#L9
> 
> 
> Во-вторых, при получении значений все равно приходится давать разные имена для value.min, range.min, ratio.min:
> https://github.com/Azmodan95/rangeSlider/blob/3917d8e519660174ede393f1ab50b27ce370066d/src/plugin/RangeSlider/Model/Model.ts#L19-L22
> 
> 
> В-третьих, объекты value, range, ratio никогда не используются целиком - для каждого min, max у тебя свои методы get, set.

Вложенные объекты я сделал с целью объединить один тип данных в одну структуру. Да и если убрать вложенность это не решит проблему с глубоким копированием объекта, так как массивы тоже копируются по ссылке, а у меня используется массив для хранения значений шкалы, и тут уже убрать вложенность не получится.
