### ISSUE TITLE
Соблюдение стандартов

### ISSUE THREAD

**Issue by imin314** [Azmodan95/rangeSlider#14]
Вот здесь лучше использовать деструктуризацию (сразу для вложенного объекта тоже): 
![Выделение_241](https://user-images.githubusercontent.com/40715953/80798959-c94d5100-8bcf-11ea-8cba-d2c7356c32b7.png)
Можно еще добавить атрибут type="button", т. к. по умолчанию будет submit.

**Comment by imin314** [comment]
Нужно отформатировать импорты по стандартам [пункт 15](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md)
![Выделение_311](https://user-images.githubusercontent.com/40715953/81682872-7e5cf480-947f-11ea-8048-bbe04cc8a6d2.png)

Еще, чтобы не писать `// eslint-disable-next-line no-unused-vars`, нужно поправить eslint конфиг. Этот блок должен быть в блоке settings, а не rules.
![Выделение_312](https://user-images.githubusercontent.com/40715953/81683326-35f20680-9480-11ea-9def-c4e3be86ffe5.png)

**Comment by Azmodan95** [comment]
> ![Выделение_312](https://user-images.githubusercontent.com/40715953/81683326-35f20680-9480-11ea-9def-c4e3be86ffe5.png)

Я может что-то не так делаю, но в settings он у меня не работает.

**Comment by imin314** [comment]
Возможно, что что-то не так делаешь. А, может быть, просто надо перезапустить VS Code.

**Comment by imin314** [comment]
Нужно добавлять элемент в дерево DOM максимально поздно (после добавления классов, атрибутов, текста в виртуальный элемент):
https://github.com/Azmodan95/rangeSlider/blob/d10459bfc84d8e040552872b16d88b72ade83225/src/plugin/RangeSlider/View/RailView/RailView.ts#L22
