### ISSUE TITLE
Observer

### ISSUE THREAD

**Issue by imin314** [Azmodan95/rangeSlider#15]
1) Из названия метода subscribe кажется, что вызвавший его объект, должен подписаться на какое-то событие:
https://github.com/Azmodan95/rangeSlider/blob/d10459bfc84d8e040552872b16d88b72ade83225/src/plugin/RangeSlider/Presenter/Presenter.ts#L43
Лучше переименовать его в addSubscriber.

2) Здесь какая-то сложная схема оповещения реализована:
https://github.com/Azmodan95/rangeSlider/blob/d10459bfc84d8e040552872b16d88b72ade83225/src/plugin/RangeSlider/View/View.ts#L123-L128

Зачем подписчику на событие 'moveThumbMin' еще раз передавать тип события?

**Comment by Azmodan95** [comment]
> 2. Здесь какая-то сложная схема оповещения реализована:
>    https://github.com/Azmodan95/rangeSlider/blob/d10459bfc84d8e040552872b16d88b72ade83225/src/plugin/RangeSlider/View/View.ts#L123-L128
> 
> Зачем подписчику на событие 'moveThumbMin' еще раз передавать тип события?

Дочерние виды генерируют события, основанной вид подписывается на них, и генерирует свое событие, презентер подписывается на события основного вида. Это сделано по причине того что у презентера нет доступа к дочерним видам, и нужно сделать некое всплытие события.

**Comment by imin314** [comment]
> > 1. Здесь какая-то сложная схема оповещения реализована:
> >    https://github.com/Azmodan95/rangeSlider/blob/d10459bfc84d8e040552872b16d88b72ade83225/src/plugin/RangeSlider/View/View.ts#L123-L128
> > 
> > Зачем подписчику на событие 'moveThumbMin' еще раз передавать тип события?
> 
> Дочерние виды генерируют события, основанной вид подписывается на них, и генерирует свое событие, презентер подписывается на события основного вида. Это сделано по причине того что у презентера нет доступа к дочерним видам, и нужно сделать некое всплытие события.

Эта схема правильная. Меня смутило, что вьюха подписывает на событие scale вот эту функцию:
```
   (event: { type: string; message: IEventData<number> }) => { 
     this.notify({ type: 'moveThumbMin', message: event.message }); 
   }, 
```
this.notify по сути получает те же аргументы, что и стрелочная функция обертка. Получается, что для любой подписки на Observer нужно оборачивать методы в дополнительные функции?

Еще логично было бы type тоже отнести в IEventData. У addSubscriber() два аргумента - первый тип события, второй функция listener, которая по идее принимает данные события (IEventData), а не event как в упомянутом выше примере кода.

**Comment by Azmodan95** [comment]
> Эта схема правильная. Меня смутило, что вьюха подписывает на событие scale вот эту функцию:
> 
> ```
>    (event: { type: string; message: IEventData<number> }) => { 
>      this.notify({ type: 'moveThumbMin', message: event.message }); 
>    }, 
> ```
> 
> this.notify по сути получает те же аргументы, что и стрелочная функция обертка. Получается, что для любой подписки на Observer нужно оборачивать методы в дополнительные функции?

Не совсем понял вопрос. Чтобы подписаться на событие, нам надо методу addSubscriber передать тип события, на который мы хотим подписаться и функцию обратного вызова, которая будет вызываться при наступлении этого события, этой функции при ее вызове передается объект события. C помощью метода notify мы сообщаем о том что событие наступило, и в качестве аргумента передаем объект с типом события и сообщением, и при этом вызываются все функции обратного вызова которые подписаны на это событие. В данном примере кода мы сначала подписываемся на событие которое происходит в scale и в функции обратного вызова, создаем оповещение о том что событии наступило, уже в основной View.

**Comment by imin314** [comment]
Вопрос можно игнорировать. Осталось еще поправить IEventData в rangeSlider.ts и закрываем ишью:
https://github.com/Azmodan95/rangeSlider/blob/7ff4b9f038331b8939432adb591285a8330947c8/src/plugin/RangeSlider/RangeSlider.ts#L39
