### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by imin314** [Azmodan95/rangeSlider#18]
Нужно обновить тесты и сделать так, чтобы покрытие тестами было не меньше 80%.

**Comment by Azmodan95** [comment]
По всем пунктам должно быть 80%? 
![Снимок](https://user-images.githubusercontent.com/51163508/84142325-41275a80-aa5d-11ea-8f2e-a85e0d5de7ae.PNG)
Как быть с приватными методами? В классе с бегунком к примеру он в основном ругается на приватные методы, где навешаиваются события
![Снимок1](https://user-images.githubusercontent.com/51163508/84142679-e0e4e880-aa5d-11ea-9ce2-d418fb5f587d.PNG) Непонятно как их вообще протестировать, да и зачем их тестировать.

**Comment by imin314** [comment]
Приватные методы тестируются через публичные, в которых они вызываются. В случае с обработчиками событий ты можешь создавать собственные события 'mousedown', 'mousemove' и т. д. и проверять генерит ли бегунок соответствующие события собственного типа.
Мне кажется, для классов вида проверять реагирует ли экземпляр на какие-то события DOM так же важно, как и тестировать вычисления в модели. Если слайдер не будет работать из-за того, что бегунок неправильно реагирует на нажатие мыши, тесты помогут найти проблему.
