### ISSUE TITLE
Демо-страница

### ISSUE THREAD

**Issue by imin314** [Azmodan95/rangeSlider#19]
Зачем добавляется класс к head?
https://github.com/Azmodan95/rangeSlider/blob/d10459bfc84d8e040552872b16d88b72ade83225/src/page/index.pug#L5

Дефолтные стили нужно устанавливать для html:
https://github.com/Azmodan95/rangeSlider/blob/d10459bfc84d8e040552872b16d88b72ade83225/src/page/index.scss#L1-L9

**Comment by imin314** [comment]
Для демо-страницы нужно тоже использовать компонентный подход, как и в задании по верстке. Нужно создавать js-классы и инициализацию панели управления и плагина проводить там:
https://github.com/Azmodan95/rangeSlider/blob/d10459bfc84d8e040552872b16d88b72ade83225/src/page/init.ts#L4-L15

**Comment by Azmodan95** [comment]
> Зачем добавляется класс к head?
> https://github.com/Azmodan95/rangeSlider/blob/d10459bfc84d8e040552872b16d88b72ade83225/src/page/index.pug#L5

Случайно не туда установил, этот класс должен был быть на html
