### ISSUE TITLE
Сливаются значения

### ISSUE THREAD

**Issue by Constantine-P** [Azmodan95/rangeSlider#24]
![image](https://user-images.githubusercontent.com/18898493/86448007-f933e480-bd37-11ea-96bc-60c66bcd0251.png)
1. При больших значениях сливаются значения шкалы
2. Неплохо бы сделать, чтобы подсказки тоже не перекрывали друг друга, когда они близко

**Comment by Azmodan95** [comment]
Исправлено.

**Comment by Constantine-P** [comment]
3. Подсказка со значением сейчас фиксированной ширины, большие значения не влазят

**Comment by Azmodan95** [comment]
Исправлено.
