### ISSUE TITLE
Ползунок отстает

### ISSUE THREAD

**Issue by Constantine-P** [Azmodan95/rangeSlider#26]
Ползунок отстает от курсора при перетаскивании. Диапазон от 0 до 10000, шаг 1, например.

**Comment by Azmodan95** [comment]
В чем конкретно отставание заключается? У меня небольшие отставания на долю секунды случаются только при быстром перемещении мыши.  
![Desktop 2020 07 21 - 12 42 21 06](https://user-images.githubusercontent.com/51163508/88039972-eea78680-cb50-11ea-8c09-9b6490be3ed9.gif)

**Comment by Constantine-P** [comment]
Чет сам не могу повторить
