### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by Constantine-P** [Azmodan95/rangeSlider#27]
У тебя сейчас для изменения состояния слайдера снаружи js'ом есть только метод update, который все слои заново создает. По-хорошему нужно обойтись без этого. Например, если меняем значение через панель, в модели должно поменяться соответствующее поле, а вью должен передвинуть ползунок, не создавая при этом заново все дом ноды слайдера. Изменение типа слайдера с двойного на одиночный или смена ориентации по-хорошему тоже не требуют создавать дом узлы заново.

**Comment by Azmodan95** [comment]
У меня так и было изначально. Предыдущий проверяющий сказал переделать https://github.com/Azmodan95/rangeSlider/issues/12#issue-610668295
