### ISSUE TITLE
Функционал слайдера

### ISSUE THREAD

**Issue by imin314** [Azmodan95/rangeSlider#7]
**Поддержка десятичных значений**
Если установить не целый шаг, то некоторые значения получаются не точными:
![Выделение_181](https://user-images.githubusercontent.com/40715953/80574159-85b9e200-8a2b-11ea-9581-5a2fbff98a88.png)

**Шаг от 0 до 1**
Я установила шаг 0.1, а бегунок двигается будто шаг равен 1:
![Peek 2020-04-29 15-11](https://user-images.githubusercontent.com/40715953/80574430-01b42a00-8a2c-11ea-8830-2a4ebb08370b.gif)

**Шаг, не кратный (max - min)**
Сейчас логика такая, что значения, по которым перемещается бегунок, всегда отсчитываются от 0. Я ставлю шаг 3, интервал от 10 до 20. Предполагается, что значения будут: 10, 13, 16, 19.
Еще, независимо от того кратны ли крайние значения шагу, слайдер позволяет их выбрать. То есть возможные значения в текущем варианте были бы: 10, 13, 16, 19, **20**.
![Выделение_182](https://user-images.githubusercontent.com/40715953/80574823-bfd7b380-8a2c-11ea-94b4-7fe8852ac43a.png)

**Отрицательные значения**
Был выбран диапазон от -100 до 0, значения -84, -67. Потом изменила диапазон на [10, 20], но значения не откорректировались в соответствии с новыми границами:
![Выделение_186](https://user-images.githubusercontent.com/40715953/80575929-8607ac80-8a2e-11ea-9a9e-d14ee4d30c53.png)
![Выделение_187](https://user-images.githubusercontent.com/40715953/80575957-8c962400-8a2e-11ea-8451-7601a11b9936.png)

**Значения на шкале**
Лучше сделать так, чтобы шаг на шкале был равен шагу слайдера. Сейчас не совсем понятно, каким образом плагин определяет шаг шкалы:
![Выделение_188](https://user-images.githubusercontent.com/40715953/80576311-2958c180-8a2f-11ea-84e5-8478f96e80a5.png)

**Ошибки в настройках плагина**
Если некорректно указать range: min, то в консоли выводится сообщение об ошибке, при этом сам слайдер продолжает работать, как будто ошибки не произошло. При этом, если те же параметры задать при инициализации слайдера, то он не будет отрисован. Мне кажется, такое поведение более логичное.

Если установить размер шага больше интервала range, слайдер продолжает работать. В инпуте для шага значение остается прежним.

**Comment by Azmodan95** [comment]
> **Значения на шкале**
> Лучше сделать так, чтобы шаг на шкале был равен шагу слайдера. Сейчас не совсем понятно, каким образом плагин определяет шаг шкалы:
> ![Выделение_188](https://user-images.githubusercontent.com/40715953/80576311-2958c180-8a2f-11ea-84e5-8478f96e80a5.png)

Размер шкалы установлен для вывода не больше 10 значений, в некоторых случаях может быть и чуть больше, так как происходит корректировка под шаг. Сделать значение шкалы равное шагу слайдера не лучшее решение, так как а если пользователь установит диапазон от 0 до 10000 с шагом 1 к примеру, у него вообще может подвиснуть браузер, да и от подобного не много информативности будет, так как значения скалы будут просто не читаемые. Скажу даже больше значения будут не читаемые даже при диапазоне от 0 до 100 с шагом 1.

**Comment by Azmodan95** [comment]
> **Ошибки в настройках плагина**
> Если некорректно указать range: min, то в консоли выводится сообщение об ошибке, при этом сам слайдер продолжает работать, как будто ошибки не произошло. При этом, если те же параметры задать при инициализации слайдера, то он не будет отрисован. Мне кажется, такое поведение более логичное.

Ну у меня были обработчики этих ошибок, в конфигурационной панели, при выносе ее из плагина за них забыл. Сейчас вернул их, и при указании некорректного значения в конфигурационной панели оно сбрасывается на прежнее.

**Comment by Azmodan95** [comment]
1

**Comment by imin314** [comment]
> Размер шкалы установлен для вывода не больше 10 значений, в некоторых случаях может быть и чуть больше, так как, происходит корректировка под шаг. Сделать значение шкалы равное шагу слайдера не лучшее решение, так как, а если пользователь установит диапазон от 0 до 10000 с шагом 1 к примеру, у него вообще может подвиснуть браузер, да и от подобного не много информативности будет, так как значения шкалы будут просто не читаемые. Скажу даже больше значения будут не читаемые даже при диапазоне от 0 до 100 с шагом 1.

Согласна, но тут я руководствовалась тем, что часто требуется шкала с конкретными значениями интервалов. И проще будет спрятать нарисованное, чем нарисовать недостающее.
В идеале можно добавить настройку, чтобы пользователь сам мог выбрать, сколько интервалов добавить на шкалу. Либо, чтобы не сильно заморачиваться, можно просто продумать логику шкалы получше, чтобы, например, она делилась на равные отрезки, а не как сейчас.

**Comment by Azmodan95** [comment]
> > Размер шкалы установлен для вывода не больше 10 значений, в некоторых случаях может быть и чуть больше, так как, происходит корректировка под шаг. Сделать значение шкалы равное шагу слайдера не лучшее решение, так как, а если пользователь установит диапазон от 0 до 10000 с шагом 1 к примеру, у него вообще может подвиснуть браузер, да и от подобного не много информативности будет, так как значения шкалы будут просто не читаемые. Скажу даже больше значения будут не читаемые даже при диапазоне от 0 до 100 с шагом 1.
> 
> Согласна, но тут я руководствовалась тем, что часто требуется шкала с конкретными значениями интервалов. И проще будет спрятать нарисованное, чем нарисовать недостающее.
> В идеале можно добавить настройку, чтобы пользователь сам мог выбрать, сколько интервалов добавить на шкалу. Либо, чтобы не сильно заморачиваться, можно просто продумать логику шкалы получше, чтобы, например, она делилась на равные отрезки, а не как сейчас.

Хорошо каким образом я должен поделить шкалу к примеру на 10 равных частей при диапазоне от 0 до 100 и шаг при этом не будет кратен 100, к примеру пусть будет 7?

**Comment by imin314** [comment]
> Хорошо каким образом я должен поделить шкалу к примеру на 10 равных частей при диапазоне от 0 до 100 и шаг при этом не будет кратен 100, к примеру пусть будет 7?

Я имела в виду вариант, когда деления на шкале не зависят от шага. То есть от 0 до 100 деления всегда будут, например, 10 20 30 40 50 и т. д. Пользователь нажимает на 10 и, если 10 не кратно шагу, то модель соответственно преобразует полученное значение и вернет кратное шагу. Но я теперь подумала и поняла, что твой вариант все-таки лучше, потому что, если поделить отрезок от 0 до 13 на 10 частей, то интервалы будут дробными.
В общем, текущую логику шкалы можно оставить, но доработать некоторые моменты все-таки надо:
При шаге 9 в диапазоне от 0 до 100 получилось, что последнее деление перекрывается максимальным интервалом. Может, максимум не добавлять на шкалу, если он не кратен шагу?
![Выделение_243](https://user-images.githubusercontent.com/40715953/80822793-a9388480-8c05-11ea-95af-c091663ceb17.png)

При некоторых значениях (когда минимум меньше 0) деления на шкале отрисовываются неравномерно:
![Выделение_248](https://user-images.githubusercontent.com/40715953/80823857-8ad38880-8c07-11ea-850b-093da5353c70.png)

**Comment by imin314** [comment]
Неточные деления на шкале остались:
![Выделение_415](https://user-images.githubusercontent.com/40715953/83806349-92d98900-a6db-11ea-8ee8-753ef8746c16.png)
