### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by imin314** [Azmodan95/rangeSlider#9]
По стандартам компании нужно давать переменным осмысленные имена, отражающие смысл хранимых данных. При этом такие названия, как data, value (в общем случае), result - очень общие и не соответствуют этому требованию.
В случае с настройками модели лучше дать им более содержательное название:
![Выделение_191](https://user-images.githubusercontent.com/40715953/80576972-48a41e80-8a30-11ea-937c-ade6edde80a6.png)

Из названий методов getValueTo() и setValueTo() не сразу ясно, что эти методы делают, из-за того что их имена заканчиваются предлогами. Может, стоит в самом объекте value: { to, from } изменить названия полей.

**Comment by imin314** [comment]
Имена методов и переменных должны быть грамматически корректными. ObserveChangeModel нужно переименовать в ObserveModelChange.
https://github.com/Azmodan95/rangeSlider/blob/b3f47b83f33153dba2cd83ac838faea021fd3b98/src/plugin/RangeSlider/Presenter/Presenter.ts#L24

**Comment by imin314** [comment]
showTooltip и showScale хранят булевы значения, поэтому их нужно именовать в соответствии с [пунктом 5](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/variablesNaming.md). 
https://github.com/Azmodan95/rangeSlider/blob/b3f47b83f33153dba2cd83ac838faea021fd3b98/src/plugin/RangeSlider/Model/IModelOptions.ts#L8-L9

**Comment by Azmodan95** [comment]
> showTooltip и showScale хранят булевы значения, поэтому их нужно именовать в соответствии с [пунктом 5](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/variablesNaming.md).
> https://github.com/Azmodan95/rangeSlider/blob/b3f47b83f33153dba2cd83ac838faea021fd3b98/src/plugin/RangeSlider/Model/IModelOptions.ts#L8-L9

Я может чего-то не понимаю, но чем данные названия не соответствуют этому пункту? Неужели нечего не зная об этих переменных, можно предположить что в них хранится какой-то другой тип данных отличный от boolean?

**Comment by imin314** [comment]
> Я может чего-то не понимаю, но чем данные названия не соответствуют этому пункту? Неужели нечего не зная об этих переменных, можно предположить что в них хранится какой-то другой тип данных отличный от boolean?

Проблема в том, что showTooltip - это глагольная форма, указывающая на действие. Такие имена принято использовать для функций. Вообще на любую фразу с глаголом можно ответить "да" или "нет" (делать что-то или не делать). Чтобы не было путаницы, где функция, а где булева переменная, нужно для последних использовать форму прилагательного (причастия, словосочетания в вопросительной форме).

**Comment by imin314** [comment]
Подобные имена методов тоже надо исправить. Название функции принято начинать с глагола, описывающего суть действия, выполняемого в функции:
https://github.com/Azmodan95/rangeSlider/blob/28821982bb35e9f6b9b9aed9d667fc6792defdc0/src/plugin/RangeSlider/Model/Model.ts#L63

**Comment by imin314** [comment]
Классу rangeSlider.ts лучше дать имя с указанием того, что в нем создается плагин jQuery. Иначе легко перепутать с RangeSlider.ts.

**Comment by imin314** [comment]
Нужно придерживаться одного стиля в именовании. Здесь, например, ты в одной переменной пишешь строчными буквами html, а ниже капсом:
https://github.com/Ilanevazno/Slider/blob/3e6faedf2cdcf10fd498624745c34e80b261b8ca/src/plugin/components/View/TooltipView/TooltipView.ts#L6-L8
